dist: trusty
language: node_js
node_js: 
  - "11"

service:
  - docker

before_script:
  - docker pull mongo
  - docker run -d -p 27017:27017 --name hackmean_mongo mongo
  - docker ps -a

script:
  - npm test
  - sonar-scanner

after_script:
  - docker rm -f hackmean_mongo

addons:
  sonarcloud:
    token:
      secure: $SONAR_TOKEN

notifications:
  slack: malikashish8:$SLACK_TOKEN
