dist: trusty
language: node_js
node_js: 
  - "10"

service:
  - docker

script:
  - sonar-scanner

addons:
  sonarcloud:
    token:
      secure: $SONAR_TOKEN

notifications:
  slack: malikashish8:$SLACK_TOKEN
