dist: trusty
language: node_js
node_js: 
  - "11"

service:
  - docker

before_install:
  - docker pull mongo
  - docker run -d -p 27017:27017 mongo
  - docker ps -a

script:
  - npm test
  - sonar-scanner

addons:
  sonarcloud:
    token:
      secure: $SONAR_TOKEN

notifications:
  slack: malikashish8:$SLACK_TOKEN
